# Generated by Django 5.1.4 on 2025-05-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_adregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adregister',
            name='address',
        ),
        migrations.RemoveField(
            model_name='adregister',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='contact',
        ),
    ]
