# Generated by Django 5.2 on 2025-05-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_no',
        ),
    ]
